### PR TITLE
Add additional readings

### PR DESCRIPTION
**Pull request by morganchen12**

### CODE REVIEW

**Comment by Ben-G** [comment]
This is more related to the structs tutorial. I was considering adding it there. Probably will. But not perfect fit for this tutorial.

**Comment by morganchen12** [comment]
:thumbsup:

**Comment by morganchen12** [comment]
Some also tangentially-related stuff about value types and Swift vs Objc, maybe think of a good way to collect additional readings?

http://realm.io/news/andy-matuschak-controlling-complexity/

**Comment by Ben-G** [comment]
Yes, there's a ton of material but I haven't really thought about how much should be linked. I probably have 5-10 talks that are related, but adding all would be confusing. Undecided on this for now

**Comment by Ben-G** [comment]
@morganchen12 Sorry, I thought these pull request were for the enum post ;)
Should decide how much cross-reference we want. Let's chat later.

**Pull request closed without merging**
